<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="theme-color" content="#080b12">
<meta name="description" content="How SAIFNEX approaches configuration integrity, privacy, least privilege, and transparent platform status.">
<link rel="icon" type="image/png" href="/favicon.png">
<title>Security & Privacy · SAIFNEX</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Space+Grotesk:wght@400;500;600;700&display=swap" rel="stylesheet">
<style>
:root{color-scheme:dark;--bg:#080b12;--panel:#0e1522;--line:rgba(153,177,218,.16);--text:#f1f5ff;--muted:#9eacc4;--blue:#4388ff;--cyan:#54e3f0;--green:#7fe0b2;--amber:#f3c879}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:radial-gradient(ellipse at 78% 0,rgba(35,92,195,.16),transparent 38%),var(--bg);color:var(--text);font:15px/1.7 'DM Sans',sans-serif}a{color:inherit;text-decoration:none}.wrap{width:min(1080px,calc(100% - 40px));margin:auto}.topbar{border-bottom:1px solid var(--line);background:rgba(8,11,18,.86)}.nav{min-height:82px;display:flex;align-items:center;justify-content:space-between;gap:20px}.logo{display:block;width:190px;max-width:48vw;height:auto}.navlinks{display:flex;align-items:center;gap:22px;color:var(--muted);font-size:13px}.btn{display:inline-flex;align-items:center;justify-content:center;padding:10px 15px;border:1px solid rgba(84,227,240,.25);border-radius:10px;background:rgba(67,136,255,.13);font-weight:700;font-size:12px}.hero{padding:76px 0 46px;max-width:790px}.eyebrow{font-size:11px;font-weight:700;letter-spacing:.16em;text-transform:uppercase;color:var(--cyan)}h1,h2,h3{font-family:'Space Grotesk',sans-serif;line-height:1.2;letter-spacing:-.035em}h1{font-size:clamp(38px,6vw,66px);margin:15px 0 18px}h1 span{background:linear-gradient(90deg,#fff,#91bcff,#54e3f0);color:transparent;background-clip:text}.lead{color:var(--muted);font-size:18px;max-width:720px}.status{display:inline-flex;align-items:center;gap:8px;margin-top:18px;padding:8px 12px;border:1px solid rgba(243,200,121,.24);border-radius:9px;background:rgba(243,200,121,.07);color:#f3d59b;font-size:11px;font-weight:700}.status i{width:7px;height:7px;border-radius:50%;background:var(--amber)}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:15px;margin:12px 0 60px}.card{padding:25px;border:1px solid var(--line);border-radius:17px;background:linear-gradient(145deg,rgba(17,27,44,.92),rgba(10,16,27,.94))}.card .num{color:var(--cyan);font-size:11px;font-weight:700;letter-spacing:.12em}.card h2{font-size:22px;margin:12px 0}.card p{color:var(--muted);margin:0}.card ul{padding-left:19px;color:var(--muted);margin:14px 0 0}.card li{margin:7px 0}.section{padding:0 0 65px}.section h2{font-size:clamp(27px,4vw,38px);margin:0 0 12px}.section>p{color:var(--muted);max-width:780px}.table{border:1px solid var(--line);border-radius:14px;overflow:hidden;margin-top:22px}.row{display:grid;grid-template-columns:1fr 1.5fr;gap:22px;padding:15px 18px;border-bottom:1px solid var(--line)}.row:last-child{border:0}.row b{font-size:13px}.row span{color:var(--muted);font-size:13px}.footer{border-top:1px solid var(--line);padding:25px 0;color:#7e8ca5;font-size:12px}.foot{display:flex;justify-content:space-between;gap:16px;flex-wrap:wrap}.foot a{color:#b8c7df}
@media(max-width:680px){.nav{padding:14px 0;align-items:flex-start;flex-direction:column}.navlinks{width:100%;gap:16px;flex-wrap:wrap}.hero{padding:50px 0 30px}.grid{grid-template-columns:1fr}.row{grid-template-columns:1fr;gap:4px}.card{padding:21px}}
</style>
</head>
<body>
<header class="topbar"><div class="wrap nav"><a href="/" aria-label="SAIFNEX home"><img class="logo" src="/saifnex-logo.png" alt="SAIFNEX — Network Intelligence"></a><nav class="navlinks" aria-label="Main navigation"><a href="/#platform">Platform</a><a href="/#architecture">Architecture</a><a href="/control-center">Control Center</a><a class="btn" href="/login">Sign in</a></nav></div></header>
<main class="wrap">
<section class="hero"><div class="eyebrow">Trust is part of the architecture</div><h1>Security by design.<br><span>Honest by default.</span></h1><p class="lead">SAIFNEX is being built to make network controls understandable without hiding the security mechanics underneath. This page separates the safeguards already present in the codebase from capabilities that still need production validation.</p><div class="status"><i></i> Development status: not a security certification</div></section>
<section class="grid" aria-label="Security principles">
<article class="card"><div class="num">01 / INTEGRITY</div><h2>Signed configuration</h2><p>Configuration publishing is designed around canonical snapshots, SHA-256 integrity checks and Ed25519 signatures.</p><ul><li>Reject unsigned or mismatched snapshots.</li><li>Keep the last known-good configuration when activation fails.</li><li>Do not disable verification to work around a missing crypto dependency.</li></ul></article>
<article class="card"><div class="num">02 / ACCESS</div><h2>Least privilege</h2><p>Network records and management operations should remain scoped to the authenticated owner or explicitly authorized role.</p><ul><li>Login attempts are rate-limited.</li><li>Node credentials are stored as hashes, not recoverable plaintext.</li><li>Initial operator setup is performed from the server CLI.</li></ul></article>
<article class="card"><div class="num">03 / PRIVACY</div><h2>Collect less</h2><p>Network visibility must serve a clear operational purpose. SAIFNEX should not expose secrets or collect raw browsing data without a clear, disclosed need.</p><ul><li>Never commit production environment files or private signing keys.</li><li>Keep credentials out of logs and public UI.</li><li>AI assistance remains optional and is not the security authority.</li></ul></article>
<article class="card"><div class="num">04 / TRANSPARENCY</div><h2>Show what is real</h2><p>Illustrative dashboard metrics must be labelled as previews until they are backed by authenticated, live telemetry.</p><ul><li>Node heartbeat is not proof of DNS enforcement.</li><li>Deployment status should reflect a real node acknowledgement.</li><li>Production readiness requires tests and deployment smoke checks.</li></ul></article>
</section>
<section class="section"><div class="eyebrow">Current implementation status</div><h2>What is implemented vs. still being built</h2><p>Security is a set of verifiable controls, not a badge. These status notes are intentionally conservative.</p><div class="table">
<div class="row"><b>Authentication</b><span>Laravel session login, session regeneration, logout invalidation and login throttling are present.</span></div>
<div class="row"><b>Network ownership</b><span>Core workspace controllers scope network access to the authenticated owner.</span></div>
<div class="row"><b>Node credential handling</b><span>Node registration generates a one-time token and stores its SHA-256 hash.</span></div>
<div class="row"><b>Configuration signing</b><span>Ed25519 signing code is present, but it requires PHP Sodium and a securely provisioned key. Do not treat signing as operational until host support and end-to-end tests pass.</span></div>
<div class="row"><b>DNS traffic enforcement</b><span>Not yet represented as operational. The Go node agent still needs a real resolver/filtering data plane and end-to-end validation.</span></div>
<div class="row"><b>Security review</b><span>This project page is not an independent audit, penetration test, compliance certification or guarantee of uninterrupted service.</span></div>
</div></section>
</main>
<footer class="footer"><div class="wrap foot"><span>© {{ date('Y') }} SAIFNEX · Security &amp; Privacy</span><span><a href="/">Home</a> · <a href="/login">Sign in</a> · <a href="/control-center">Control Center</a></span></div></footer>
</body></html>
